"""Point-in-time factor tear sheets for fast, honest hypothesis triage.

The caller must supply already-lagged factors and explicitly constructed
forward returns. This module diagnoses cross-sectional behavior; it does not
create labels, tune a strategy, or produce promotion evidence.
"""

from __future__ import annotations

import math
import re

import numpy as np
import pandas as pd

from edgestack.exceptions import ValidationError
from edgestack.recommendation.hashing import stable_hash
from edgestack.research.schemas import FactorDiagnosticsV1
from edgestack.validation.metrics import effective_sample_size

_FORWARD_RETURN = re.compile(r"^forward_return_(\d+)$")


def _rank_correlation(left: pd.Series, right: pd.Series) -> float:
    valid = left.notna() & right.notna()
    x = left.loc[valid]
    y = right.loc[valid]
    if len(x) < 3 or x.nunique() < 2 or y.nunique() < 2:
        return float("nan")
    return float(x.rank(method="average").corr(y.rank(method="average")))


def _mean_and_t_stat(values: list[float]) -> tuple[float, float]:
    array = np.asarray([value for value in values if np.isfinite(value)], dtype=float)
    if len(array) < 2:
        return (float(array.mean()) if len(array) else 0.0, 0.0)
    mean = float(array.mean())
    standard_deviation = float(array.std(ddof=1))
    if standard_deviation <= 0:
        return mean, 0.0
    information = effective_sample_size(array)
    standard_error = standard_deviation / math.sqrt(max(1.0, information))
    return mean, mean / standard_error if standard_error > 0 else 0.0


def _frame_hash(frame: pd.DataFrame) -> str:
    hashes = pd.util.hash_pandas_object(frame, index=False).astype("uint64")
    return stable_hash(
        {
            "columns": tuple(str(column) for column in frame.columns),
            "dtypes": tuple(str(dtype) for dtype in frame.dtypes),
            "row_hashes": tuple(int(value) for value in hashes),
        }
    )


def analyze_factor(
    frame: pd.DataFrame,
    *,
    factor_name: str,
    quantiles: int = 5,
    group_column: str | None = None,
) -> FactorDiagnosticsV1:
    """Return deterministic cross-sectional IC, quantile, and turnover diagnostics.

    Required columns are ``date``, ``symbol``, ``factor`` and one or more
    ``forward_return_<sessions>`` columns. Duplicate date/symbol rows are
    rejected instead of silently aggregated.
    """
    if not 2 <= quantiles <= 20:
        raise ValidationError("factor diagnostics quantiles must be between 2 and 20")
    required = {"date", "symbol", "factor"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValidationError(f"factor diagnostics missing columns: {missing}")
    if group_column is not None and group_column not in frame.columns:
        raise ValidationError(f"factor diagnostics missing group column {group_column!r}")
    horizon_columns: list[tuple[int, str]] = []
    for column in frame.columns:
        match = _FORWARD_RETURN.match(str(column))
        if match:
            horizon_columns.append((int(match.group(1)), str(column)))
    horizon_columns.sort()
    if not horizon_columns:
        raise ValidationError(
            "factor diagnostics require explicit forward_return_<sessions> columns"
        )
    if len({horizon for horizon, _ in horizon_columns}) != len(horizon_columns):
        raise ValidationError("forward-return horizons must be unique")

    columns = ["date", "symbol", "factor", *(name for _, name in horizon_columns)]
    if group_column is not None:
        columns.append(group_column)
    work = frame.loc[:, columns].copy()
    work["date"] = pd.to_datetime(work["date"], errors="raise")
    work["symbol"] = work["symbol"].astype(str)
    if work.duplicated(["date", "symbol"]).any():
        raise ValidationError("factor diagnostics received duplicate date/symbol rows")
    numeric = ["factor", *(name for _, name in horizon_columns)]
    for column in numeric:
        work[column] = pd.to_numeric(work[column], errors="coerce")
        work.loc[~np.isfinite(work[column]), column] = np.nan
    work = work.sort_values(["date", "symbol"], kind="mergesort").reset_index(drop=True)
    data_hash = _frame_hash(work)
    warnings = [
        "Diagnostic only: this tear sheet cannot satisfy any promotion gate.",
        "Forward returns must be generated by the guarded point-in-time label pipeline.",
    ]

    valid_cross_sections = work.groupby("date", sort=True)["factor"].transform("count")
    dropped_sessions = int(work.loc[valid_cross_sections < quantiles, "date"].nunique())
    work = work.loc[valid_cross_sections >= quantiles].copy()
    work = work.dropna(subset=["factor"])
    if work.empty or work["date"].nunique() < 2:
        raise ValidationError(
            "factor diagnostics need at least two cross-sections with one asset per quantile"
        )
    if dropped_sessions:
        warnings.append(
            f"Dropped {dropped_sessions} sessions with fewer than {quantiles} factor values."
        )

    percentile = work.groupby("date", sort=True)["factor"].rank(method="first", pct=True)
    work["factor_quantile"] = np.ceil(percentile * quantiles).clip(1, quantiles).astype(int)

    mean_by_quantile: dict[str, dict[str, float]] = {}
    top_bottom: dict[str, float] = {}
    rank_ic_mean: dict[str, float] = {}
    rank_ic_t: dict[str, float] = {}
    neutral_ic_mean: dict[str, float] = {}
    monotonicity: dict[str, float] = {}
    for horizon, column in horizon_columns:
        key = str(horizon)
        quantile_means = work.groupby("factor_quantile", sort=True)[column].mean()
        mean_by_quantile[key] = {
            str(index): float(value)
            for index, value in quantile_means.items()
            if np.isfinite(value)
        }
        daily_ic = [
            _rank_correlation(group["factor"], group[column])
            for _, group in work.groupby("date", sort=True)
        ]
        ic_mean, ic_t = _mean_and_t_stat(daily_ic)
        rank_ic_mean[key] = ic_mean
        rank_ic_t[key] = ic_t

        spreads: list[float] = []
        for _, group in work.groupby("date", sort=True):
            means = group.groupby("factor_quantile")[column].mean()
            if 1 in means.index and quantiles in means.index:
                spread = float(means.loc[quantiles] - means.loc[1])
                if np.isfinite(spread):
                    spreads.append(spread)
        top_bottom[key] = float(np.mean(spreads)) if spreads else 0.0
        ordered = pd.Series(
            [quantile_means.get(index, np.nan) for index in range(1, quantiles + 1)],
            index=range(1, quantiles + 1),
            dtype=float,
        )
        monotonicity[key] = _rank_correlation(
            pd.Series(ordered.index, dtype=float), ordered.reset_index(drop=True)
        )

        if group_column is not None:
            neutral = work[["date", group_column, "factor", column]].copy()
            neutral["factor"] -= neutral.groupby(["date", group_column])["factor"].transform("mean")
            neutral[column] -= neutral.groupby(["date", group_column])[column].transform("mean")
            neutral_daily = [
                _rank_correlation(group["factor"], group[column])
                for _, group in neutral.groupby("date", sort=True)
            ]
            neutral_ic_mean[key] = _mean_and_t_stat(neutral_daily)[0]

    turnover: dict[str, float] = {}
    dates = tuple(sorted(work["date"].unique()))
    for quantile in range(1, quantiles + 1):
        changes: list[float] = []
        previous: set[str] | None = None
        for session in dates:
            current = set(
                work.loc[
                    (work["date"] == session) & (work["factor_quantile"] == quantile),
                    "symbol",
                ].astype(str)
            )
            if previous is not None and previous:
                changes.append(1.0 - len(previous & current) / len(previous))
            previous = current
        turnover[str(quantile)] = float(np.mean(changes)) if changes else 0.0

    trial_charge = len(horizon_columns) * quantiles * (2 if group_column is not None else 1)
    identity = {
        "factor_name": factor_name,
        "data_hash": data_hash,
        "quantiles": quantiles,
        "horizons": tuple(horizon for horizon, _ in horizon_columns),
        "group_column": group_column,
    }
    return FactorDiagnosticsV1(
        diagnostics_id=stable_hash(identity)[:24],
        factor_name=factor_name,
        data_hash=data_hash,
        observations=len(work),
        sessions=int(work["date"].nunique()),
        quantiles=quantiles,
        horizons=tuple(horizon for horizon, _ in horizon_columns),
        mean_return_by_quantile=mean_by_quantile,
        top_minus_bottom_mean=top_bottom,
        rank_ic_mean=rank_ic_mean,
        rank_ic_t_stat=rank_ic_t,
        group_neutral_rank_ic_mean=neutral_ic_mean,
        monotonicity=monotonicity,
        quantile_turnover=turnover,
        trial_charge=trial_charge,
        warnings=tuple(warnings),
    )
